[package]
name = "mahardhika"
version = "0.1.0"
authors = ["Muhammad Fuad Hasan <mfuadhasan@fastmail.fm>"]

[dependencies]
argparse = "*"
conduit-mime-types = "^0.7"
regex = "^0.1"
threadpool = "^0.1"
time = "^0.1"
url = "^0.2"

[[bin]]
name = "mahardhika"
doc = false
test = false

